# Generated by Django 4.2.26 on 2026-01-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulder',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
