FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PORT=8000 \
    DJANGO_SETTINGS_MODULE=app.settings \
    PYTHONPATH=/app

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./

EXPOSE 8000

CMD ["sh", "-c", "\
  mkdir -p /app/media && \
  python manage.py makemigrations --noinput && \
  python manage.py migrate --noinput && \
  python manage.py collectstatic --noinput && \
  gunicorn app.wsgi:application --bind 0.0.0.0:${PORT} --workers 1 --threads 2 --timeout 180 --access-logfile - --error-logfile - --log-level debug\
"]