# Generated by Django 4.2.26 on 2025-11-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boulder',
        ),
    ]
